[debug]구글로그인 기능: 백그라운드 스레드 동작 이슈해결 및 topViewContorller 함수기능 개선
1OS-DevTeam/TodoPang pull request #80
Opened 2024-02-28 08:51 UTC by crossbell8368

## Motivation
* #77 
* #79 

## Key Changes
* 'AuthGoogleServices' 의 이슈관련 함수에 Attribute 추가
* 'GoogleLoginHelper' 내 'func topViewController' 로직개선
  
## To Reviewers
자세한 내용은 commit message 확인 부탁드립니다!

2024-03-02 02:28 UTC, naldal commented on teamplan/Sources/Util/GoogleLoginHelper.swift
> +        var topController = rootViewController
재귀함수를 만들어서 사용하는게 좀더 우아한 방법이지 않을까 합니다.
```
private func findTopViewController(from viewController: UIViewController) -> UIViewController {
    if let presentedViewController = viewController.presentedViewController {
        return findTopViewController(from: presentedViewController)
    } else if let navigationController = viewController as? UINavigationController,
              let visibleViewController = navigationController.visibleViewController {
        return findTopViewController(from: visibleViewController)
    } else if let tabBarController = viewController as? UITabBarController,
              let selectedViewController = tabBarController.selectedViewController {
        return findTopViewController(from: selectedViewController)
    }
    return viewController
}
```

2024-03-02 02:29 UTC, naldal requested changes
최상위 ViewController를 찾는 private 메서드를 사용해보시는것을 권장드립니다

2024-03-05 04:54 UTC, crossbell8368 commented on teamplan/Sources/Util/GoogleLoginHelper.swift
> +        var topController = rootViewController
확인이 늦어서 죄송합니다ㅠ

재귀방식으로 구성할지, 단순 반복으로 구성할지 고민하다가
동작과정을 보기 쉬운 단순반복 형태로 구성했었으나, 확실히 가독성의 저하와 복잡성이 증가한것 같습니다ㅠ

리뷰주신 재귀함수 방식을 적용해보도록 하겠습니다!
꼼꼼한 리뷰 감사합니다!

2024-03-05 05:46 UTC, naldal commented
> GoogleLoginHelper 클래스의 'func topViewController() -> UIViewController?' 함수의 private 선언을 말씀하신게 맞을까요..?
> 
> 현재 google소셜로그인 부분에서 해당 함수를 호출하여 사용중입니다!
> 
> 해당 함수의 private 전환이 이뤄진다면 함수위치 변경으로만 가능하다고 생각됩니다ㅠ
> 
> 함수가 구글 소셜로그인 부분에서만 사용되니, 해당 파일에 관련함수들을 모으는 방향을 말씀하신게 맞을까요..?

internal 함수와 private 함수를 분리하는게 좋다는 뜻이었습니다. 혼동을 드려 죄송합니다

현재 internal 함수인 func topViewController() -> UIViewController? 의 주된 관심사는 최상위의 뷰컨트롤러를 리턴하는 겁니다.
이를 구현하기 위해 반복적(while(true)든, 재귀이든) 으로 상위 뷰컨트롤러를 찾고있습니다.

정리하자면 func topViewController() 메서드는 세가지 역할을 수행하고 있습니다.

1. Scene의 rootVC를 찾는다.
2. 이를 토대로 무한히 반복하여 최상위 VC를 찾는다.
3. 찾은 최상위 VC를 리턴한다.

여기서부터는 가독성 영역의 문제이지만 가독성의 문제가 곧 유지보수의 영역이기도 하니 제안드리는 것은:
- 무한히 반복하여 최상위 VC를 찾는 과정을 private 메서드로 분리.
- 최상위 VC를 찾았다면 이를 단순 리턴하여 internal 메서드에서는 무한히 반복하여 최상위 VC를 찾는 구현 메서드에서 관심사 분리.
입니다.

2024-03-05 06:34 UTC, crossbell8368 commented
아하! 현재 internal 함수인 'func topViewController() -> UIViewController?' 에서 핵심기능 파트를 private 함수로 추출하여 구성하는 편이 유지보수 측면에 이점이 될 것 같다는 말씀이시군요!

확실히 그 부분이 말씀주신 가독성, 유지보수 측면에서 이점이 더 클 것 같습니다!

자세하고 깔끔한 코멘트 감사드립니다 👍

남겨주신 내용을 반영한 코드로 다시 찾아뵙겠습니닷!

2024-03-06 06:32 UTC, naldal approved these changes

2024-03-07 12:57 UTC, merged